language: python

# use container-based infrastructure
sudo: false

deploy:
  provider: pypi
  user: cheffe
  password:
    secure: DlsGcyzZ6yMMLxvJ07eXx+QHL1GpNcFs8liw89NWXpghgd9lcCZX1bkM+oMNyRL6rBFFvLpj+DdiSDeeCDPpmWhLOXopNmxXpY0SjE2mFO3OesZsYSlIUHXjESO+tTyqjaYzdChil2YgMBKtNb8JRKhfdIBD4JuYptUpbKNwZAY=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: baztian/dbapi-compliance

python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'

env:
  matrix:
    - DB_NAME=psycopg DRIVER=psycopg2 PGUSER=postgres

install:
  - if [ -n "$DRIVER" ]; then pip install $DRIVER ;fi

script:
  - python test_${DB_NAME}_dbapi20.py
